export interface Job {
  company: string;
  aboutCompany: string;
  position: string;
  image: string;
  location: string;
  postedTime: string;
  employmentType: string;
  applications: string;
  division: string;
  salary: string;
  description: string;
  qualifications: string;
}

export const jobData: Job[] = [
  {
    company: 'Google',
    aboutCompany: 'Google is searching for a company',
    position: 'Data Scientist',
    image: 'https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-512.png',
    location: 'São Paulo - Remote',
    postedTime: '1 min ago',
    employmentType: 'Full-time',
    applications: '700',
    division: 'Data Engine',
    salary: '$350k',
    description: 'As a Data Scientist at Google, you will be responsible for analyzing large datasets to develop insights and solutions to complex business problems. You will work closely with cross-functional teams to design and implement data-driven strategies.',
    qualifications: 'Master\'s or PhD in Computer Science, Statistics, Mathematics, or related field. Proficiency in programming languages such as Python or R. Strong analytical and problem-solving skills.',
  },
  {
    company: 'Microsoft',
    aboutCompany: 'Microsoft is a big tech company',
    position: 'Software Engineer',
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg',
    location: 'Seattle - On-site',
    postedTime: '5 mins ago',
    employmentType: 'Contract',
    applications: '3000',

    division: 'Cloud Computing',
    salary: '$300k',
    description: 'As a Software Engineer at Microsoft, you will be responsible for designing, developing, and maintaining software applications and solutions. You will collaborate with team members to deliver high-quality code and ensure the scalability and reliability of products.',
    qualifications: 'Bachelor\'s or Master\'s degree in Computer Science or related field. Proficiency in programming languages such as C++, Java, or C#. Strong problem-solving and communication skills.',
  },
  {
    company: 'Apple',
    aboutCompany: 'Apple Inc. is an American multinational technology company',
    position: 'iOS Developer',
    image: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg',
    location: 'Cupertino - On-site',
    postedTime: '10 mins ago',
    employmentType: 'Full-time',
    applications: '1000',
    division: 'iOS Development',
    salary: '$320k',
    description: 'As an iOS Developer at Apple, you will be responsible for designing and developing applications for iOS devices. You will collaborate with cross-functional teams to deliver innovative and user-friendly solutions to meet customer needs.',
    qualifications: 'Proficiency in Swift and Objective-C. Experience with iOS frameworks such as UIKit and Core Data. Strong understanding of mobile app development best practices.',
  },
  {
    company: 'Amazon',
    aboutCompany: 'Amazon is an American multinational technology company',
    position: 'Cloud Solutions Architect',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/1024px-Amazon_logo.svg.png',
    location: 'Seattle - Remote',
    postedTime: '15 mins ago',
    employmentType: 'Full-time',
    applications: '1500',
    division: 'Amazon Web Services',
    salary: '$340k',
    description: 'As a Cloud Solutions Architect at Amazon, you will be responsible for designing and implementing cloud-based solutions for customers. You will collaborate with sales and engineering teams to deliver scalable and reliable architectures on AWS cloud platform.',
    qualifications: 'Strong understanding of cloud computing concepts and AWS services. Experience in designing and implementing enterprise-scale solutions. AWS certification is a plus.',
  },
  {
    company: 'Facebook',
    aboutCompany: 'Facebook is an American online social media and social networking service',
    position: 'Frontend Developer',
    image: 'https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg',
    location: 'Menlo Park - On-site',
    postedTime: '20 mins ago',
    employmentType: 'Full-time',
    applications: '1000',
    division: 'Frontend Development',
    salary: '$310k',
    description: 'As a Frontend Developer at Facebook, you will be responsible for developing user interfaces for web applications. You will work closely with designers and backend engineers to implement interactive and responsive designs.',
    qualifications: 'Proficiency in HTML, CSS, and JavaScript. Experience with frontend frameworks such as React or Angular. Strong understanding of web standards and best practices.',
  },
  
  {
      company: 'IBM',
      aboutCompany: 'IBM is a leading technology and consulting company',
      position: 'AI Engineer',
      image: 'https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg',
      location: 'New York - Remote',
      postedTime: '25 mins ago',
      employmentType: 'Full-time',
      applications: '900',
      division: 'Artificial Intelligence',
      salary: '$330k',
      description: 'As an AI Engineer at IBM, you will be involved in designing and implementing AI solutions for various business applications. You will work with cutting-edge technologies to develop machine learning models and algorithms.',
      qualifications: 'Bachelor\'s or Master\'s degree in Computer Science, Engineering, or related field. Proficiency in programming languages such as Python, Java, or C++. Experience with machine learning frameworks such as TensorFlow or PyTorch.',
  },
  {
      company: 'Netflix',
      aboutCompany: 'Netflix is a global provider of streaming entertainment',
      position: 'Senior Backend Engineer',
      image: 'https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg',
      location: 'Los Gatos - Remote',
      postedTime: '30 mins ago',
      employmentType: 'Full-time',
      applications: '599',
      division: 'Backend Development',
      salary: '$320k',
      description: 'As a Senior Backend Engineer at Netflix, you will be responsible for designing and developing scalable backend systems to support the Netflix streaming platform. You will work on high-impact projects to improve performance, reliability, and scalability.',
      qualifications: 'Bachelor\'s or Master\'s degree in Computer Science or related field. Strong programming skills in languages like Java, Python, or Scala. Experience with distributed systems and cloud computing technologies.',
  },
  {
      company: 'Tesla',
      aboutCompany: 'Tesla, Inc. is an American electric vehicle and clean energy company',
      position: 'Autopilot Software Engineer',
      image: 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Tesla_logo.png',
      location: 'Palo Alto - On-site',
      postedTime: '35 mins ago',
      employmentType: 'Full-time',
      applications: '300',
      division: 'Autonomous Driving',
      salary: '$340k',
      description: 'As an Autopilot Software Engineer at Tesla, you will be part of the team developing software for Tesla\'s Autopilot system. You will work on cutting-edge technologies to enable autonomous driving capabilities in Tesla vehicles.',
      qualifications: 'Bachelor\'s or Master\'s degree in Computer Science, Electrical Engineering, or related field. Strong programming skills in languages like C/C++ and Python. Experience with robotics, computer vision, or machine learning is a plus.',
  },
  {
    company: 'Twitter',
    aboutCompany: 'Twitter is an American microblogging and social networking service',
    position: 'Backend Developer',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/X_logo_2023.svg/1024px-X_logo_2023.svg.png',
    location: 'San Francisco - Remote',
    postedTime: '40 mins ago',
    employmentType: 'Full-time',
    applications: '800',
    division: 'Backend Development',
    salary: '$310k',
    description: 'As a Backend Developer at Twitter, you will be responsible for designing and implementing scalable backend systems to support Twitter\'s platform. You will work with a team of engineers to develop and maintain high-performance APIs and services.',
    qualifications: 'Bachelor\'s or Master\'s degree in Computer Science or related field. Proficiency in programming languages such as Java, Scala, or Python. Experience with distributed systems and database technologies.',
},
{
    company: 'Uber',
    aboutCompany: 'Uber Technologies, Inc. is an American technology company',
    position: 'Machine Learning Engineer',
    image: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Uber_logo_2018.png',
    location: 'San Francisco - Remote',
    postedTime: '45 mins ago',
    employmentType: 'Full-time',
    applications: '500',
    division: 'AI & Machine Learning',
    salary: '$330k',
    description: 'As a Machine Learning Engineer at Uber, you will be responsible for developing and deploying machine learning models to solve complex problems in areas such as pricing, routing, and fraud detection. You will work with large-scale data and collaborate with cross-functional teams to drive impact.',
    qualifications: 'Master\'s or PhD in Computer Science, Statistics, or related field. Strong programming skills in languages such as Python, Java, or Scala. Experience with machine learning frameworks and tools such as TensorFlow, PyTorch, or scikit-learn.',
},
{
    company: 'Airbnb',
    aboutCompany: 'Airbnb, Inc. is an American vacation rental online marketplace',
    position: 'Frontend Engineer',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Airbnb_Logo_B%C3%A9lo.svg/1024px-Airbnb_Logo_B%C3%A9lo.svg.png',
    location: 'San Francisco - Remote',
    postedTime: '50 mins ago',
    employmentType: 'Full-time',
    applications: '700',
    division: 'Frontend Development',
    salary: '$320k',
    description: 'As a Frontend Engineer at Airbnb, you will be responsible for building and optimizing user interfaces for Airbnb\'s web and mobile applications. You will collaborate with designers and backend engineers to deliver a seamless and engaging user experience.',
    qualifications: 'Proficiency in HTML, CSS, and JavaScript. Experience with modern frontend frameworks such as React, Vue.js, or Angular. Strong understanding of web performance optimization and responsive design principles.',
}

  
];
